---
name: Deploy Sanitas

on:    # yamllint disable-line rule:truthy
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  backend-deploy:
    name: Backend Deployment
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.get_url_step.outputs.url }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          audience: sts.amazonaws.com
          region: us-east-2
          role-to-assume: ${{ secrets.BACKEND_DEPLOY_AWS_ROLE }}
      - name: Building Backend
        # yamllint disable-line rule:line-length
        run: nix develop --impure . --command bash -c "cd sanitas_backend/ && sam build"
      - name: Deploying Backend
        # yamllint disable-line rule:line-length
        run: nix develop --impure . --command bash -c "cd sanitas_backend/ && yes | sam deploy --parameter-overrides PostgresURL=${{ secrets.DB_URL }}"
      - name: Saving Backend URL
        id: get_url_step
        # yamllint disable-line rule:line-length
        run: nix develop --impure . --command bash -c "cd sanitas_backend/ && echo url=$(sam list stack-outputs --stack-name sanitas-backend --output json | jq .[0].OutputValue | sed -e 's/^\"//' -e 's/\"$//') >> $GITHUB_OUTPUT"

  frontend-deploy:
    name: Frontend Deployment
    needs: backend-deploy
    environment:
      name: build
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/configure-pages@v4
      - name: Building frontend
        # yamllint disable-line rule:line-length
        run: nix develop --impure . --command bash -c "cd sanitas_frontend/ && yarn && BACKEND_URL=${{ needs.backend-deploy.outputs.backend_url }} yarn build --base=/Sanitas/"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./sanitas_frontend/dist

      - uses: actions/deploy-pages@v4
        id: deployment
