---
name: Deploy Frontend

on:    # yamllint disable-line rule:truthy
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: build and deploy
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/configure-pages@v4
      - run: |
          nix develop --impure . --command bash -c \
            "cd sanitas_frontend/ && yarn && yarn build"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./sanitas_frontend/dist

      - uses: actions/deploy-pages@v4
        id: deployment
