---
name: Frontend Lint and Tests
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  testAndLinting:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#cicdFrontend --command bash {0}
        working-directory: sanitas_frontend
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Linting
        run: yarn && yarn run lint
      - name: Testing
        run: yarn && yarn test
