---
name: Frontend Lint and Tests
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  testAndLinting:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#cicdFrontend --command bash {0}
        working-directory: sanitas_frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Linting
        run: yarn && yarn run lint
      - name: Testing
        run: yarn && yarn test
